# Generated by Django 2.2.1 on 2019-06-19 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfoodapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saved',
            name='Food_id_foodissub',
        ),
        migrations.AddField(
            model_name='saved',
            name='Food_id_foodissub',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='foodissub', to='myfoodapp.Food'),
        ),
        migrations.RemoveField(
            model_name='saved',
            name='Food_id_foodsub',
        ),
        migrations.AddField(
            model_name='saved',
            name='Food_id_foodsub',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='foodsub', to='myfoodapp.Food'),
        ),
    ]
