# Generated by Django 2.2.1 on 2019-06-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfoodapp', '0002_auto_20190619_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='img_food',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
